name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      release:
        description: 'With release'
        required: true
        type: boolean

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Linux'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'Mac'
            platform:  'darwin/amd64'
            os: 'macos-latest'

    name: Build for ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Install Wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build Binary (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: wails build -clean -platform ${{ matrix.build.platform }}

      - name: Build Binary (Mac)
        if: runner.os == 'macOS'
        shell: bash
        run: wails build -clean -platform ${{ matrix.build.platform }}

      - name: Compress Binary
        uses: vimtor/action-zip@v1.2
        with:
          files: build/bin/
          dest: ${{ runner.os }}-${{ inputs.version }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: ${{ runner.os }}-${{ inputs.version }}.zip
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release ${{ inputs.version }}-${{ github.run_id }}.${{ github.run_number }}
    if: inputs.release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/downloaded-artifact
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ inputs.version }}-build.${{ github.run_id }}.${{ github.run_number }}
          name: ${{ inputs.version }} Build ${{ github.run_id }}.${{ github.run_number }}
          files: |
            ${{ github.workspace }}/downloaded-artifact/Linux-${{ inputs.version }}.zip
            ${{ github.workspace }}/downloaded-artifact/MacOs-${{ inputs.version }}.zip