name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      release:
        description: 'With release'
        required: true
        type: boolean

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Linux'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'Mac'
            platform:  'darwin/amd64'
            os: 'macos-latest'

    name: Build for ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Install Wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Build Binary (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: wails build -clean -platform ${{ matrix.build.platform }}

      - name: Build Binary (Mac)
        if: runner.os == 'macOS'
        shell: bash
        run: wails build -clean -platform ${{ matrix.build.platform }}

      - name: Convert Icon PNG to ICNS (Mac)
        if: runner.os == 'macOS'
        run: |
          ICON_SRC="build/appicon.png"
          ICONSET_DIR="temp.iconset"
          ICON_DEST="build/darwin/icon.icns"

          mkdir -p "$ICONSET_DIR"

          # Buat berbagai ukuran PNG (diperlukan oleh iconutil)
          sips -z 16 16     "$ICON_SRC" --out "$ICONSET_DIR/icon_16x16.png"
          sips -z 32 32     "$ICON_SRC" --out "$ICONSET_DIR/icon_16x16@2x.png"
          sips -z 32 32     "$ICON_SRC" --out "$ICONSET_DIR/icon_32x32.png"
          sips -z 64 64     "$ICON_SRC" --out "$ICONSET_DIR/icon_32x32@2x.png"
          sips -z 128 128   "$ICON_SRC" --out "$ICONSET_DIR/icon_128x128.png"
          sips -z 256 256   "$ICON_SRC" --out "$ICONSET_DIR/icon_128x128@2x.png"
          sips -z 256 256   "$ICON_SRC" --out "$ICONSET_DIR/icon_256x256.png"
          sips -z 512 512   "$ICON_SRC" --out "$ICONSET_DIR/icon_256x256@2x.png"
          sips -z 512 512   "$ICON_SRC" --out "$ICONSET_DIR/icon_512x512.png"
          cp "$ICON_SRC" "$ICONSET_DIR/icon_512x512@2x.png"

          # Convert to .icns
          iconutil -c icns "$ICONSET_DIR" -o "$ICON_DEST"

          # Remove temp icon
          rm -rf temp.iconset

      - name: Create .app bundle manually (Mac)
        if: runner.os == 'macOS'
        run: |
          APP_NAME="wails-action2"
          APP_VERSION="${{ inputs.version }}"
          APP_DIR="build/bin/${APP_NAME}.app"
          BIN_PATH="build/bin/${APP_NAME}"

          mkdir -p "${APP_DIR}/Contents/MacOS"
          mkdir -p "${APP_DIR}/Contents/Resources"

          # Copy binary
          cp "${BIN_PATH}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"
          cp "build/darwin/info.plist" "${APP_DIR}/Contents/Info.plist"

          # Optional: copy icon
          if [ -f build/darwin/icon.icns ]; then
            cp build/darwin/icon.icns "${APP_DIR}/Contents/Resources/"
          fi

      - name: Install create-dmg (Mac)
        if: runner.os == 'macOS'
        run: brew install create-dmg

      - name: Create DMG (Mac)
        if: runner.os == 'macOS'
        run: |
          create-dmg \
            --volname "wails-action2" \
            --volicon "build/darwin/icon.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "wails-action2.app" 200 190 \
            --hide-extension "wails-action2.app" \
            --app-drop-link 600 185 \
            "Mac-${{ inputs.version }}.dmg" \
            "build/bin/wails-action2.app"


      - name: Compress Binary
        uses: vimtor/action-zip@v1.2
        with:
          files: build/bin/
          dest: ${{ runner.os }}-${{ inputs.version }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binary
          path: ${{ runner.os }}-${{ inputs.version }}.zip
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release ${{ inputs.version }}-${{ github.run_id }}.${{ github.run_number }}
    if: inputs.release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/downloaded-artifact
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ inputs.version }}-build.${{ github.run_id }}.${{ github.run_number }}
          name: ${{ inputs.version }} Build ${{ github.run_id }}.${{ github.run_number }}
          files: |
            ${{ github.workspace }}/downloaded-artifact/Linux-${{ inputs.version }}.zip
            ${{ github.workspace }}/downloaded-artifact/Mac-${{ inputs.version }}.zip